### ISSUE TITLE
Failed to parse update metadata

### ISSUE THREAD

**Issue by cptolemy** [YahnisElsts/plugin-update-checker#213] opened 2018-07-12 17:53 UTC
Hi,

Congrats for the plugin - I've been using it for a while without problems :) But today, when in debug mode, I noticed this warning:

Notice: Failed to parse update metadata. Try validating your .json file with http://jsonlint.com/ in /home/perfil/public_html/wp-content/plugins/myPlugin/plugin-update-checker/Puc/v4p4/Metadata.php on line 35

Any idea to fix this?

Kind regards

**Comment by YahnisElsts** [comment] 2018-07-13 09:22
Usually that message means that the metadata URL - that is, the URL that you pass to `buildUpdateChecker()` - returned something that is not valid JSON. You've probably already checked for that, but if not, please run it through [the JSON validator](https://jsonlint.com/) that's mentioned in the notice.

Aside from invalid JSON, another way this could happen is if the URL returns an error message of some kind instead of the expected update information. That can be caused by overloaded servers, bad network connection, misconfigured firewall, a bug in the script that outputs the update information, and so on. If the problem is intermittent, it probably has something to do with the network or the server.

**Comment by cptolemy** [comment] 2018-07-13 09:29
Good morning

Thanks for the reply. You are right: the network to where the request is sent, sometimes doesn't respond correctly - it's an astronomy website with many requests and sometimes its shutdown for some hours -  thus an error in the response format. I made a new script, to first verify if the server is available and responsive. Only then I call your script.

Maybe I'll modify your code - in Metadata.php - to return a "no update found" if that happens.

Thanks :)

**Comment by YahnisElsts** [comment] 2018-07-13 14:10
If I recall correctly, the update checker already treats that situation as "no update found". It will try to check for updates again later. The notice is there to help plugin/theme authors detect configuration problems like incorrect metadata URLs.

**Comment by cptolemy** [comment] 2018-07-13 16:03
Hi

Yes, it's logical. But the problem is that if the user (not the developer) is trying to check for an update - for instance - it will see a writen (and alarming) warning on Wordpress, not a single notification, like "not available at the moment" or "try again later". In the automatic mode it might be best not to show anything. What do you think?

Kind regards,

**Comment by YahnisElsts** [comment] 2018-07-13 17:22
Correct me if I'm wrong, but doesn't WordPress hide PHP notices by default? This means most users will never see the message you mentioned. 

If the user clicks the "check for updates" link below the plugin description then they *will* get a warning like "Could not determine if updates are available for Plugin Name" and an additional error message. This is probably a pretty uncommon events since plugins already check for updates automatically. Still, if you want to hide that warning, then modifying the Metadata class would be a way to do that. Another place to look is the `getLastRequestApiErrors()` method in `UpdateChecker.php`. You could override that hide *all* manual update check errors instead of just those that are related to JSON validation.

**Comment by cptolemy** [comment] 2018-07-13 17:56
Hi,

Yes, by default PHP does hide those notices. However most of the users out there (a great percentage of my clients for instance) don't have permission to disable the debug mode (set to true) the providers insist to turn on. So pretty unpleasant notices, warnings and errors appear. Most of them are harmless. If we have full control over our website, this won't happen. But to these users - without many practise - it does. So, I'm just trying to figure a way to avoid "panics" - like it happened  with the new WPress release that uses a some what different syntax, and gives many unecessary warnings (not errors).

Still, thanks for leading me to where I can adapt the code to my users needs :)

You have been very helpful.

Kind regards,

**Comment by YahnisElsts** [comment] 2018-07-13 18:04
All right, I'll close the issue now. If you have further questions or feedback, feel free to re-open it.

**Closed by YahnisElsts** 2018-07-13 18:04 UTC
