### ISSUE TITLE
Single Use Plugin

### ISSUE THREAD

**Issue by stingray82** [YahnisElsts/plugin-update-checker#336] opened 2020-01-30 00:40 UTC
Firstly thanks, this is really helpful software, my next goal is to make this so I can update any and all plugins using it when setting up a new site. With that in mind, I have just uploaded a Single Source of this library as a plugin other plugins can reference you can view it here: https://github.com/stingray82/ninja-updater

it's early days I only started this evening and I have made some progress in getting it to check other plugins, I was wondering if anyone using this who understands PHP / Wordpress Better than I can help with a query from the dev branch 
https://github.com/stingray82/ninja-updater/blob/Dev/ninja-updater.php

I have added a function to get slugs and file plugin folders to be able to run the updates
_get_plugin_update_slugs_ its called, it works but it only appends to the new array the last one in alphabetical order, so I've made a mistake somewhere, I am also looking at a way to pass them out as an array and then access them in _Check_Others_ when I want it to nest through and check for updates, so I think to do this I will need to plugin name/slug and the full install location out of the  _get_plugins()_ function.

Example of what I am getting out of _get_plugin_update_slugs_ 
Array
(
    [key_carry] => ph-pdf-mockups/ph-pdf-mockups.php
    [slug_carry] => projecthuddle-pdf-mockups-addon
)

But it expects it to be full of the all the plugins I have on the dev site not just the last one in alphabetical order.

Does anyone have any suggestions or know of some code where this has been done, they could point me in the right direction?

Thanks again, and feel free to collab if you wish on the plugin

~ Stingray

**Comment by YahnisElsts** [comment] 2020-01-31 12:40
I think the reason why `get_plugin_update_slugs` returns only one result is that the code in the `foreach` loop overwrites `$plugnsX` instead of adding new entries to it. I would recommend two changes to this function:

1. Set `$plugnsX` to a new array before the loop. 
    ```php
    $plugnsX = array();
    ```
2. Change the line that assigns a value to `$plugnsX` to this:
    ```php
    $plugnsX[] = compact ("key_carry","slug_carry");
    ```
    (Basically, just add "[]" after the array name. See the PHP documentation on [modifying arrays](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying).)

**Comment by stingray82** [comment] 2020-01-31 15:01
Hi, Thanks you are correct thank you very much for the help its appreciated and thanks for the reference it helps to understand why it was wrong

I think it's now working, but its causing issues (it's checking all plugins) but when they don't exist in the repo they are causing issues:

Debug logs below:
[31-Jan-2020 14:45:33 UTC] PHP Fatal error:  Uncaught Error: Call to a member function isMuPlugin() on null in /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/updates/Puc/v4p8/Plugin/UpdateChecker.php:315
Stack trace:
#0 /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/updates/Puc/v4p8/Plugin/UpdateChecker.php(61): Puc_v4p8_Plugin_UpdateChecker->isUnknownMuPlugin()
#1 /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/updates/Puc/v4p8/Factory.php(86): Puc_v4p8_Plugin_UpdateChecker->__construct('http://useraccount...', '/home/useraccount/...', 'hello-dolly', 12, '', '')
#2 /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/ninja-updater.php(47): Puc_v4p8_Factory::buildUpdateChecker('http://useraccount...', '/home/useraccount/...', 'hello-dolly')
#3 /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/ninja-updater.php(17): Check_Others()
#4 /home/useraccount/public_html/Dev/wp-settings.php(360): include_once('/home/useraccount/...')
#5 /home/useraccount/public_html/Dev/wp-config.php(93): require_once('/home/ in /home/useraccount/public_html/Dev/wp-content/plugins/ninja-updater/updates/Puc/v4p8/Plugin/UpdateChecker.php on line 315

obviously hello-dolly isn't in my repo, it will only contain my own plugin and premium ones I can legally use, so I need some error handling for when the Puc_v4p8_Plugin_UpdateChecker throws up this error.

Thank you again
~ Stingray

**Comment by YahnisElsts** [comment] 2020-01-31 15:06
I think this could be caused by a recently reported bug. The bug has been fixed in the master branch, but I haven't made a new release yet. Try the code from the [master branch](https://github.com/YahnisElsts/plugin-update-checker/archive/master.zip).

**Comment by stingray82** [comment] 2020-01-31 16:43
Yes that was what was causing that, I've got it working on my own and premium plugins, haven't tried themes yet but that's on my next list

Regarding Premium plugins:

I've added Smush-pro and updraft premium to this 
![image](https://user-images.githubusercontent.com/11146912/73556697-daa78580-4447-11ea-9fef-09e1c40c6292.png)

I have wound back the version in the plugin reuploaded the original to the repo and updraft works fine, but smush has something stoping it any idea on how to override this so all plugins can be updated from my repo if a version exists in my repo?

I am guessing it can be done otherwise the GPL clubs wouldn't be able to do it but can't find a reference online to do so..

**Comment by YahnisElsts** [comment] 2020-01-31 17:25
I haven't used Smush Pro myself and I'm not familiar with how it handles updates. It sounds like it might have its own update implementation (not based on PUC). Maybe you could ask the plugin author about that?

**Comment by stingray82** [comment] 2020-01-31 17:44
Yes you are correct for anyone else that stumbles on this just remove the dashboard and rename or remove plugins/wp-smush-pro/core/external/dash-notice/wpmudev-dash-notification.php and the PUC will then take over.
![image](https://user-images.githubusercontent.com/11146912/73561651-4510f380-4451-11ea-9792-4f1de729783f.png)

Now it updates from my repo, I will push these changes to the master now

Thanks for all your help

**Closed** 2020-02-07 12:04 UTC
Labels: question
