### ISSUE TITLE
feature idea: support for dashicons-admin-plugins introduced in WordPress 4.9

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#155] opened 2017-11-17 22:47 UTC
I found that with WordPress 4.9 the plugin dashicons were added to the page WordPress updates:
![grafik](https://user-images.githubusercontent.com/158669/32972239-2f44d0fe-cbe9-11e7-8c4f-4257006f2721.png)

If would be great if this would also be supported by the plugin-update-checker (and/or plugin-update-server - not sure where this would need to be added)

**Comment by YahnisElsts** [comment] 2017-11-17 22:55
This is a duplicate of #153. 

Also, I believe those are just regular icons, not Dashicons (well, the placeholder is a Dashicon).

**Closed by YahnisElsts** 2017-11-17 22:55 UTC
Labels: duplicate

**Comment by robertharm** [comment] 2017-11-17 23:03
thanks for the prompt reply!
