### ISSUE TITLE
Bitbucket Plugin Updates

### ISSUE THREAD

**Issue by kwcjr** [YahnisElsts/plugin-update-checker#112] opened 2017-06-26 06:40 UTC
I can't seem to get the plugin to say it needs an update using a private bit bucket repo with an OAuth Consumer key setup. I did however get it to fire off using the json file. Updating via Bitbucket is working great with Themes...Am I doing something wrong?

**Comment by YahnisElsts** [comment] 2017-06-26 11:53
Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and look at the "PUC (your-slug)" panel. Does everything seem correct there? Try clicking the "Request Info" button. Does the output look valid?

**Comment by kwcjr** [comment] 2017-06-26 23:51
I have installed Debug Bar prior to posting. I did read the posts about clicking "Request Info" button, but I am just not seeing any output on the "PUC(your-slug)" page, it's completely blank. And I don't know where this "Request Info" button is located. I have added all the define( ) lines to the config file as well. 
![debug bar](https://user-images.githubusercontent.com/9300827/27564860-a5533af4-5aa8-11e7-89ba-782a0184230d.png)

**Comment by kwcjr** [comment] 2017-06-27 00:57
First two screen shots are local - The third is the Comment Header in the main plugin file that has the Update Script with OAuth Consumer Creds. 

![download 1](https://user-images.githubusercontent.com/9300827/27566212-b4228cca-5ab1-11e7-8a5e-2a4bd4e0021d.png)
![download 3](https://user-images.githubusercontent.com/9300827/27566214-b4249bdc-5ab1-11e7-8f38-f943cd170152.png)
![download 2](https://user-images.githubusercontent.com/9300827/27566213-b4237a72-5ab1-11e7-837f-597e6aeeb4a9.png)

**Comment by YahnisElsts** [comment] 2017-06-27 07:48
Make sure you have the latest version of the update checker. Another user recently reported that some older versions don't work with the latest version of Debug Bar and just show a blank page.

**Comment by kwcjr** [comment] 2017-06-29 02:10
Ok, so that fixes the plank page in Dubug Bar. Now by Clicking Request Info button it gives me "Failed to retrieve plugin info from the metadata URL."... Which is in the third screenshot above. The Version comments are in the main plugin file in the root of the project repository and I have double checked my OAuth creds repeatedly and also tried using just the basic comments such as /* comment */  So I am still in the same boat.

**Comment by kwcjr** [comment] 2017-06-29 06:19
Woohoo I figured it out! :) 

Ok, so when I set my theme up I just used the full URL given to me from Bitbucket like so "https://keith_crain@bitbucket.org/keith_crain/kcs-branding.git" and it worked just fine but for my plugin it didn't work like that. 

I finally re-read "https://bitbucket.org/user-name/repo-name" and said you know let me try "https://keith_crain@bitbucket.org/keith_crain/kcs-branding/" and bloop the data came back. So i just had to drop off the ".git" and use the folder name instead. 

For me I guess that part of the setup confused me just a bit -- but I am just one user. I love the ease of use and functionality this has brought to my workflow. 

Thank you for your attention and trying to help me.

**Comment by kwcjr** [comment] 2017-06-29 06:23
![screenshot_11](https://user-images.githubusercontent.com/9300827/27674024-cd2144ac-5c71-11e7-8091-0164c90ebb2e.png)

WOOHOO! Thanks again for your help :) Cheers

**Comment by kwcjr** [comment] 2017-06-29 07:43
Welp I was only able to update one time :\ Now i changed the version to 1.0.4 and it's still pulling 1.0.3

**Comment by kwcjr** [comment] 2017-06-29 07:46
OOHHHH k so with plugins I HAVE to use Tags. hew that was confusing. heh back on track sry :P

**Comment by kwcjr** [comment] 2017-06-29 07:48
OOHHHH k so with plugins I HAVE to use Tags. hew that was confusing. heh back on track sry :P

Success! :D 
![success](https://user-images.githubusercontent.com/9300827/27676909-c5cbd6a2-5c7d-11e7-862a-fedbb1182a6e.png)

**Comment by YahnisElsts** [comment] 2017-06-29 10:27
You don't *have to* use tags. Wait, let me double-check the BitBucket-related code...

...Yep, tags are not required. You can use tags, or you can just have a branch (not necessarily `master`) and update the `Version` header to release a new version. 

The only catch is that you can't have *both*: if you have any tags that look like version numbers, the update checker won't even look at the `Version` header in the `master` branch. Could that explain why 1.0.4 wasn't showing up initially?

**Comment by kwcjr** [comment] 2017-06-29 11:46
Yeah that's exactly what had happened. I added a tag in an earlier
commit trying to get it  to work with the other URL I was using. One I
added a new tag  it popped up.

**Comment by YahnisElsts** [comment] 2017-06-29 12:25
All right, it sounds like the issue is resolved. I'll close it.

**Closed by YahnisElsts** 2017-06-29 12:25 UTC
