### ISSUE TITLE
(minor) Plugin update count incorrect

### ISSUE THREAD

**Issue by Blindmikey** [YahnisElsts/plugin-update-checker#64] opened 2016-07-22 21:56 UTC
It seems that this is causing the plugin update count on the menu items:
- Dashboard->Updates
- Plugins

To show `1` in a red circle, despite all plugins being up to date. 

WP 4.5.3
Fresh install

**Comment by YahnisElsts** [comment] 2016-07-24 17:01
I can't seem to reproduce that on my site. Are you sure it's not a configuration issue of some kind? Here are a few things to check:

- If you explicitly specify the plugin slug when initialising the update checker, does the slug match the plugin directory name?
- Is the plugin file name that's passed to the update checker the correct file?
- Is the plugin installed in `mu-plugins`? WordPress doesn't support updates for mu-plugins, but it will still show the red `1` bubble when an update is available.

**Comment by YahnisElsts** [comment] 2016-08-07 10:23
Any news on this?

**Comment by Blindmikey** [comment] 2016-08-11 19:27
I should have time to look further into this next week.

**Comment by YahnisElsts** [comment] 2016-10-25 09:31
Did you get a chance to look into the update count issue?

**Comment by hallshouse** [comment] 2017-02-05 17:25
I'm having this issue as well, but also my sample plugin continues to show an update is available.
In my example, my plugin is version 1.0.1 and it says a version 1.0.1 update is available.

I'm not using a readme.txt file in the plugin folder, instead I'm only using the plugin-slug.json meta-data.

The sample plugin updates correctly and the plugin updated message displays, but when I refresh the browser, I get that an update is available form this version to this same version.

Any idea what the cause of this could be?

**Comment by YahnisElsts** [comment] 2017-02-06 12:31
> The sample plugin updates correctly and the plugin updated message displays, but when I refresh the browser, I get that an update is available from this version to this same version.

That's normal for the example plugin. The 2.0 "update" that it downloads is actually just another copy of version 1.1, so it will keep saying that an update is available. It's deliberately set up that way to make it easier to test update notifications.

> I'm not using a readme.txt file in the plugin folder, instead I'm only using the plugin-slug.json meta-data.

That should be fine. The readme.txt will be completely ignored when you're using a JSON file.

> In my example, my plugin is version 1.0.1 and it says a version 1.0.1 update is available.

Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and look at the "PUC (your-plugin-slug)" panel in the "Debug" menu. Does everything look right in the "Configuration" and "Status" sections? What's the content of the "Checked version" and "Cached update" fields?

**Comment by hallshouse** [comment] 2017-02-06 13:57
Thanks for getting back @YahnisElsts 
I have attached a file showing the Debug Bar results.
It all looks fine to me.
![update_server_debug_results](https://cloud.githubusercontent.com/assets/11246769/22649737/4c3320e6-ec4a-11e6-81d8-6417aaf7a998.jpg)

**Comment by YahnisElsts** [comment] 2017-02-06 14:32
I think I see the problem: the version number in the plugin header is "v1.0.2", but the version number in the JSON document is "1.0.2" (no "v" prefix). These numbers are not equal. Internally, the update checker uses the [version_compare](http://php.net/manual/en/function.version-compare.php) function to compare version numbers, and I suspect that this function will treat a version number that doesn't start with a digit as invalid.

Solution: remove the "v" prefix from the `Version: v1.0.2` header.

**Comment by hallshouse** [comment] 2017-02-06 15:10
Yup, that was it. Thanks very much @YahnisElsts

**Comment by YahnisElsts** [comment] 2017-02-06 15:21
All right, that's good to hear. 

Since the original reporter hasn't responded in 5+ months, I'll go ahead and assume they've got it fixed as well, and close the issue.

**Closed by YahnisElsts** 2017-02-06 15:21 UTC
