### ISSUE TITLE
Can't get this to work with composer :(

### ISSUE THREAD

**Issue by MichaelSmi** [YahnisElsts/plugin-update-checker#74] opened 2016-12-03 09:56 UTC
Hi there,

I really love your lib very much. I successfully used it for multiple plugins.
Right now I'm in a big wordpress plugin project and I came to the point, where I need more and more libraries... I'd like to use your lib with composer. I used the packagist include for your lib but sadely I'm not able to use your lib by autoloading it with composer.
Could you please add a installation how to snippet to your readme or give me a hint on how to use your lib with composer?!

Thanks.

**Comment by YahnisElsts** [comment] 2016-12-03 10:12
This library doesn't specify autoloading information. You can install or update it with Composer, but you still have to include `plugin-update-checker.php` directly.

**Comment by YahnisElsts** [comment] 2016-12-07 11:33
By the way, to make the most of autoloading, this library would probably have to use namespaces. This would increase minimum requirements to PHP 5.3+. Personally I'd be OK with that, but I'm not sure if it's practical considering that WordPress itself still supports PHP 5.2. Thoughts?

**Comment by michaeltorbert** [comment] 2016-12-07 14:24
While I'd love to see increased adoption of modern versions of PHP among all hosts, we aren't there yet.

Personally, I'd be very sad if the requirements were bumped to 5.3+. We use PUC for All in One SEO Pack Pro with 10s of 1000s of users, many of whom are still on 5.2.

**Comment by YahnisElsts** [comment] 2016-12-07 14:35
Out of interest, do you have any stats about what percentage of your users is on 5.2? WodPress.org [stats page](https://wordpress.org/about/stats/) says that about 6% of all installs are still on that version, but I wonder if that number might be mostly composed of old, unmaintained sites that never install updates anyway.

**Comment by michaeltorbert** [comment] 2016-12-07 14:40
Not at the moment, but if you ping me later I can go through the stats we've collected and see. I've often wondered the same thing. We could probably even compare PHP version to AIOSEOP Pro version to determine what percentage of people update plugins but not PHP.

The problem is, even if we're talking about 1% of PUC installs that are kept current, that's still a lot of people.

**Comment by YahnisElsts** [comment] 2017-03-08 13:34
Update: I've made [a log parser](https://github.com/YahnisElsts/wp-update-server-stats) for wp-update-server that can collect and visualize PHP and plugin version statistics (among other things). 

It's not immediately useful because I haven't been logging PHP version data, but it should produce some interesting results once the next plugin release is out.

**Comment by tikitariki** [comment] 2017-04-02 21:13
Ah, thank you @MichaelSmi for making this issue. I was scratching my head here too.

@YahnisElsts, WordPress is going to start upping [the minimum PHP version requirement soon](https://wptavern.com/wordpress-to-bump-recommended-php-version-from-5-6-to-7-0-by-the-middle-of-2017).

In the mean time, I think it would be very useful to add a note to the README about this lib not working with Composer's autoloader. I'm willing to do a PR with the added information. Thank you for the awesome plugin.

**Comment by YahnisElsts** [comment] 2017-04-03 08:19
> @YahnisElsts, WordPress is going to start upping the minimum PHP version requirement soon.

That article talks about the minimum *recommended* version, which is, unfortunately, not the same as the minimum *required* version. The minimum requirement is still PHP 5.2.4 and I haven't heard of any plans to increase that.

> In the mean time, I think it would be very useful to add a note to the README about this lib not working with Composer's autoloader.

The master branch already supports Composer autoloading. If you need it right now, you could change the required version in your `composer.json` to `dev-master`, e.g. 
```json
"require": {
    "yahnis-elsts/plugin-update-checker": "dev-master"
}
```

**Comment by connerbw** [comment] 2017-09-20 16:55
Works fine? 

_(Fixed in https://github.com/YahnisElsts/plugin-update-checker/releases/tag/v4.1)_

**Comment by YahnisElsts** [comment] 2017-09-21 08:05
Yep, autoloader support was added a while ago. Thank you for the reminder. I'll close this issue now.

**Closed by YahnisElsts** 2017-09-21 08:05 UTC
