### ISSUE TITLE
Parsing readme.txt file - broken ULs

### ISSUE THREAD

**Issue by karolispx** [YahnisElsts/plugin-update-checker#68] opened 2016-09-14 14:27 UTC
Hey! There's an issue with parsing the readme.txt file. ULs aren't closing properly causing all ULs to be inside the first UL. I've attached screenshots showing what's happening. Is there a way to fix this? 

Parsing libraries used seem to be up to date.

![screen shot 2016-09-14 at 15 24 50](https://cloud.githubusercontent.com/assets/10049454/18516130/b624f06a-7a8f-11e6-80d3-857955bca0d1.png)
![screen shot 2016-09-14 at 15 26 33](https://cloud.githubusercontent.com/assets/10049454/18516132/b62ee3cc-7a8f-11e6-8551-0fd4503fcbbd.png)
![screen shot 2016-09-14 at 15 24 26](https://cloud.githubusercontent.com/assets/10049454/18516131/b627586e-7a8f-11e6-9fcb-46e5060d7b25.png)

Thanks!

**Comment by YahnisElsts** [comment] 2016-09-14 15:19
The update checker only parses readme.txt when the plugin is hosted on GitHub. Are you using the `PucGitHubChecker` class? If not then the parsing is handled by WordPress core and the problem is most likely somewhere else.

**Comment by karolispx** [comment] 2016-09-14 15:23
The plugin is indeed hosted in a private github repository and that's where the data is being pulled from.

**Comment by YahnisElsts** [comment] 2016-09-14 16:04
All right, I can reproduce the issue. I'll look into it.

**Comment by YahnisElsts** [comment] 2016-09-14 16:43
Should be fixed now. Let me know if I missed anything.

**Closed** 2016-09-14 16:42 UTC

**Comment by karolispx** [comment] 2016-09-15 09:19
that did the job, thanks!
