### ISSUE TITLE
debug bar fatal error with 4.3.1

### ISSUE THREAD

**Issue by pjv** [YahnisElsts/plugin-update-checker#152] opened 2017-11-15 15:57 UTC
with debug bar activated, upgrading from 4.2 to 4.3.1 resulted in this hard crash:

`Fatal error: Uncaught Error: Call to undefined method Puc_v4_Factory::normalizePath() in /mnt/wp_plugins/woocommerce-inventory-notifier/plugin-updates/Puc/v4p3/DebugBar/Extension.php:93 Stack trace: #0 /mnt/wp_plugins/woocommerce-inventory-notifier/plugin-updates/Puc/v4p3/DebugBar/Extension.php(40): Puc_v4p3_DebugBar_Extension->getLibraryUrl('/css/puc-debug-...') #1 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(298): Puc_v4p3_DebugBar_Extension->enqueuePanelDependencies('') #2 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 /srv/www/wordpress-default/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /srv/www/wordpress-default/public_html/wp-content/plugins/debug-bar/debug-bar.php(118): do_action('debug_bar_enque...') #5 /srv/www/wordpress-default/public_html/wp-content/plugins/debug-bar/debug-bar.php(50): Debug_Bar->enqueue() #6 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(298): Debug_Bar->i in /mnt/wp_plugins/woocommerce-inventory-notifier/plugin-updates/Puc/v4p3/DebugBar/Extension.php on line 93`

**Comment by YahnisElsts** [comment] 2017-11-15 16:17
I can't reproduce that. Tested with WP 4.9 and Debug Bar 0.9: no errors, no warnings and no notices.

Are sure you've got all of the latest files and something on the server isn't caching the old version?

**Comment by pjv** [comment] 2017-11-15 16:30
Running WP 4.8.3 here. It's a development server in a vagrant (VVV) box. PHP 7.0. There is no caching installed. Debug bar 0.9.

I tried rebooting the box just to make sure. Same crash.

Any info beyond that stack trace I can give you?

**Comment by YahnisElsts** [comment] 2017-11-15 16:59
I guess you could verify that the class `Puc_v4_Factory` actually has a static method called `normalizePath`. It's in `/Puc/v4/Factory.php`. 

Also, are you initialising the update checker via `Puc_v4_Factory::buildUpdateChecker()` or are you creating a new instance directly?

**Comment by pjv** [comment] 2017-11-15 17:23
Yup, I see `public static function normalizePath($path) {...` in `/Puc/v4/Factory.php`.

I'm initializing with `Puc_v4_Factory::buildUpdateChecker()`.

**Comment by YahnisElsts** [comment] 2017-11-15 18:11
Do you have any *other* plugins active that use this update checker?

**Comment by janeks** [comment] 2017-11-15 18:19
Same error. 
It's related to Plugin Update Checker Library 4.2. If some other plugin uses the older library we may get the error depending on which Puc_v4_Factory class going to be registered first old or new.
Old  calls: wp_normalize_path;  New: normalizePath
Fixed by renaming Puc_v4_Factory to Puc_v43_Factory.

**Comment by pjv** [comment] 2017-11-15 18:25
yup, that was it. Sorry I should have thought of that. I had several different plugins using PUC active and had only updated one of them to 4.3.1 - the others were still on 4.2. When I deactivated those still on version 4.2 the crash went away.

**Comment by YahnisElsts** [comment] 2017-11-15 18:30
All right, this is a bug. It looks like #136 broke backwards compatibility with older 4.x versions and I didn't notice. I'll need to fix this later.

**Comment by YahnisElsts** [comment] 2017-11-16 15:05
I've just committed a patch that should fix this bug. Please try the master branch.

**Comment by pjv** [comment] 2017-11-17 18:51
Current master branch works in conjunction with 4.2 for me.

**Comment by pjv** [comment] 2017-11-18 18:25
I just looked more closely at the commit to fix this issue. Am I reading it right that we need to modify the initialization code from `Puc_v4_Factory::buildUpdateChecker()` to `Puc_v4p3_Factory::buildUpdateChecker()`? Is that a one time thing, or will we have to modify our plugin code for each PUC update from now on?

When I tested the latest master branch, I didn't make that change so I must have been instantiating an old version of the update checker from the code in the "other" plugin with 4.2 inside it. 

I just tested again with the new init call and it's not crashing, but even explicitly calling the new 4.3.1+ code, it seems like it's still instantiating the older code because I am not seeing the new `View Details` link in the plugin manager beneath the plugin that is running the master HEAD for update checker unless i first deactivate the other plugin running 4.2. When I deactivate the other plugin, then I see `View Details`.

**Comment by YahnisElsts** [comment] 2017-11-18 18:32
> Is that a one time thing, or will we have to modify our plugin code for each PUC update from now on?

You'll probably need to do it almost every time you update PUC. I know it's annoying, but, as far as I know, there's just no better way to have multiple versions of the same library loaded at the same time. If you can think of a better solution, I'd love to hear it!

> I just tested again with the new init call and it's not crashing, but even explicitly calling the new 4.3.1+ code, it seems like it's still instantiating the older code because I am not seeing the new View Details link [...]

Hmm, maybe I'll need to bump the version number again for that. I'll look into that next week.

**Comment by pjv** [comment] 2017-11-18 18:34
> Hmm, maybe I'll need to bump the version number again for that. I'll look into that next week.
See the edit in my post above.

**Comment by pjv** [comment] 2017-11-18 18:49
> You'll probably need to do it almost every time you update PUC. I know it's annoying, but, as far as I know, there's just no better way to have multiple versions of the same library loaded at the same time. If you can think of a better solution, I'd love to hear it!

So the scheme that you were using in version 4.2 for example where you had both `/v4` and `/v4p2` under `/puc` and it was always trying to build the update checker with the latest minor version is what got broken in #136?

**Comment by YahnisElsts** [comment] 2017-11-18 18:54
As long as there are no backwards-incompatible changes, it is possible to keep the same `Puc_vXpY_Factory` name. However, that doesn't work if you need access to all of the latest features, so I probably won't be doing that in the future.

**Comment by rogerlos** [comment] 2018-07-08 04:18
Completely untested and probably a bad idea in any case, but could you do something like this?

https://gist.github.com/rogerlos/fbfc04a2abb104fd3a5556270532fedd

**Comment by YahnisElsts** [comment] 2018-07-08 09:18
That's an interesting approach, but I don't think it solves the big problem: as a plugin/theme developer, if you want to make sure that you get a compatible version of the library, you still need to put the version number in your source code and change it when you update PUC. In the original implementation that means changing `Puc_vXpY_*` class names. With your alternative factory, it means changing the arguments you pass to the `version()` method.

**Comment by YahnisElsts** [comment] 2019-07-06 11:40
I'm closing this issue because it has been inactive for almost a year and the original error has been resolved.

**Closed by YahnisElsts** 2019-07-06 11:40 UTC
Labels: bug
