### ISSUE TITLE
Error: Class 'Puc_v4_Factory' not found 

### ISSUE THREAD

**Issue by sgiles77** [YahnisElsts/plugin-update-checker#477] opened 2022-01-21 21:08 UTC
I just released a plugin update that upgrades the update checker code to version 4.11. Testing went fine on my server, but two different sites in the field reported the Class 'Puc_v4_Factory' not found error when attempting to execute the update. I noticed you already addressed this error (#321) in 4.8.1, but it appears to have resurfaced. The two sites are running WP 5.8.3 and PHP 7.3 or higher. I am struggling to debug the issue since I can't reproduce it locally. 

Code in the main plugin file looks like this:

require 'plugin-update-checker/plugin-update-checker.php';
$MyUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
    'http://sgcustomwebsolutions.com/path-to-json-file/dynamic-user-directory-exclude-user-filter.json',
    __FILE__,
    'dynamic-user-directory-exclude-user-filter'
);

**Comment by YahnisElsts** [comment] 2022-01-21 21:12
Closing this because it's a duplicate of #476.

**Closed by YahnisElsts** 2022-01-21 21:12 UTC
