### ISSUE TITLE
Bad renaming when I updated from http:www/website/wp-admin/plugins.php

### ISSUE THREAD

**Issue by SalahKhouildi** [YahnisElsts/plugin-update-checker#33] opened 2015-07-27 10:01 UTC
Hi,

When I update from http:www/website/wp-admin/plugins.php the plugin folder name  is rename like
username-pluginrepository-0b6ff025db8a4578bea1fdf10ff80c7c35da5efe
and if I'll update from http://website//wp-admin/update-core.php the plugin folder is good and doesn't change.
What can I do for not change the plugin folder name when I update it?

Thanks a lot for your answer.

Best regards,

Salah.

**Comment by YahnisElsts** [comment] 2015-07-27 10:46
That's a known issue with previous releases (it was caused by changes in WP core), but it should be fixed in the current master branch. Try that.

**Comment by SalahKhouildi** [comment] 2015-07-27 11:10
Thanks for your answer? What should I try?

**Comment by SalahKhouildi** [comment] 2015-07-27 12:15
It works! :)

**Comment by YahnisElsts** [comment] 2015-07-27 12:19
All right, that's good to hear. I'll close the issue for now; feel free to re-open it if the same problem happens again.

**Comment by SalahKhouildi** [comment] 2015-07-27 12:25
In fact, I have the same problem if I'll update from Manage WP.

**Comment by YahnisElsts** [comment] 2015-07-28 09:16
The cause is probably the same. To know how to rename the folder, the update checker needs to know which plugin is being updated. ManageWP probably uses a custom updater or a custom updater skin, and the update checker doesn't know how to get the plugin file name from that.

I don't have a good place to test this, but 70011dbb524cb250884ba44b361dcf31e5279247 might fix that. Try the latest master again (i.e. re-download it).

**Comment by SalahKhouildi** [comment] 2015-07-28 09:26
Hi Yahnis,

It's working with Manage WP!

Thanks a lot!

**Comment by YahnisElsts** [comment] 2015-07-28 09:29
All right, I'll package this patch as a proper release later today.

**Comment by SalahKhouildi** [comment] 2015-07-28 10:15
Cool! Does your plugin works with themes?

**Comment by YahnisElsts** [comment] 2015-07-28 10:19
This one doesn't, but I have another library that does:
http://w-shadow.com/blog/2011/06/02/automatic-updates-for-commercial-themes/

It's a bit less flexible that this one, but it works for many themes.

**Comment by SalahKhouildi** [comment] 2015-07-28 12:20
Is it work with private Github repository?

**Comment by YahnisElsts** [comment] 2015-07-28 13:59
No, that library doesn't support GitHub-based updates.

**Closed** 2015-10-08 18:03 UTC
Labels: bug

**Comment by lengthofrope** [comment] 2016-02-29 14:09
I'm using the 2.2 release and WordPress 4.4.2 and the issue of not renaming seems to be back. When updating the plugin from the plugins screen (through ajax), it does not change the directory name back to the plugins directory name, resulting in a 'This plugin is disabled because the plugin file cannot be found' message.

**Comment by YahnisElsts** [comment] 2016-02-29 17:17
Try the master branch, it has a couple of recent bug fixes. 

If that doesn't work, could you tell me a bit more about your setup? For example, are you using the JSON metadata format, or loading updates from GitHub? What does your .zip directory structure look like?

**Comment by lengthofrope** [comment] 2016-02-29 23:30
The master branch is working indeed. Can you give an estimate when v3.0 arrives? Thnx!

**Comment by YahnisElsts** [comment] 2016-03-01 12:14
Soon-ish. 3.0 is pretty stable and I'll probably release it as-is. Just need to write up the release notes.

**Comment by lengthofrope** [comment] 2016-03-01 14:34
Hurray! Thanks for your hard work!
