### ISSUE TITLE
Bad renaming when I updated from Manage WP

### ISSUE THREAD

**Issue by SalahKhouildi** [YahnisElsts/plugin-update-checker#34] opened 2015-07-27 12:35 UTC
Hi,

When I update from Manage WP the plugin folder name is rename like
username-pluginrepository-0b6ff025db8a4578bea1fdf10ff80c7c35da5efe

What can I do for not change the plugin folder name when I update it?

Thanks a lot for your answer.

Best regards,

Salah.

**Comment by YahnisElsts** [comment] 2015-07-28 09:10
Duplicate of #33

**Closed by YahnisElsts** 2015-07-28 09:10 UTC
Labels: duplicate
