### ISSUE TITLE
GitHub API Error: HTTP status code: 404. puc-github-http-error

### ISSUE THREAD

**Issue by gerardpp** [YahnisElsts/plugin-update-checker#423] opened 2021-04-01 15:56 UTC
Hello. I am trying to connect my plugin with my private remote repo through Github. I haven't had any luck in achieving this. I created a Personal Access Token on Github and that is the token I am using in the config params. Other than that, my repository url is correct, I am not using any hooks in my plugins's main php file. I copied all the files in a folder inside my project with the exact same naming convention. I created a tag on GitHub with my current stable tag number. There is nothing else I can think of that might be causing this error. This is what I am getting:

Could not determine if updates are available for Dinner in the Sky Reservations.

GitHub API error. Base URL: "/repos/:user/:repo/releases/latest", HTTP status code: 404. puc-github-http-error
GitHub API error. Base URL: "/repos/:user/:repo/tags", HTTP status code: 404. puc-github-http-error
GitHub API error. Base URL: "/repos/:user/:repo/branches/master", HTTP status code: 404. puc-github-http-error
Could not retrieve version information from the repository. This usually means that the update checker either can't connect to the repository or it's configured incorrectly. puc-no-update-source

Please help

**Comment by YahnisElsts** [comment] 2021-04-01 16:37
Most likely, either the repository URL or the access token is incorrect.

Could you show the code that you use to initialize the update checker? You can replace the access token with a placeholder value before posting.

**Comment by rpc4mv** [comment] 2021-06-13 00:57
Running into the same issue. I created a personal access token following [these steps](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).

And have this at the bottom of my `functions.php` file:
```
$check_updates = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Dwellers/wp-yup-theme',
	__FILE__,
	'yup'
);
$check_updates->setAuthentication('ghp_****');
```

I verified my access token works using
```
curl -u rpc4mv:ghp_**** https://api.github.com/repos/Dwellers/wp-yup-theme/branches/master
```

**Comment by YahnisElsts** [comment] 2021-06-13 11:07
Assuming that both the repository URL and the token are correct, I don't know what could cause a 404 error in this context. I tested it with a private repository just before writing this comment and that worked fine, so it's probably not an API compatibility issue.

Maybe you could try logging the HTTP requests and see if the API URL or the full 404 response provides any clues?

**Comment by JiveDig** [comment] 2023-01-06 17:37
I'm seeing this with all (most) of my plugins using PUC. Many customers are seeing it as well. This is with all public repos too. Happy to test but not exactly sure how. Can you give me some direction on what to look into?

![dHwTHHms](https://user-images.githubusercontent.com/540990/211067227-4af20133-1a92-4821-8023-5dc662f9f810.png)

**Comment by YahnisElsts** [comment] 2023-01-06 17:48
If you can reliably reproduce the problem, I recommend setting up HTTP request logging and checking what exactly GitHub isn't happy with. There should be more details in the API response body.

There was a "Core Control" plugin that I used to use to log HTTP requests sent by WP plugins, but it's no longer available. Maybe you could use [Log HTTP Requests](https://github.com/FacetWP/log-http-requests) or, for a local site, something like Wireshark.

**Comment by JiveDig** [comment] 2023-01-06 17:48
I'm seeing this on plugins that use Releases and others that do not and strictly use a version number in the plugin header.

**Comment by JiveDig** [comment] 2023-01-06 17:53
Okay wow, that was easy, thanks.
```
{
  "headers": {},
  "body": "{\"message\":\"API rate limit exceeded for {IP removed for privacy}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n",
  "response": {
    "code": 403,
    "message": "Forbidden"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```
Seems like the error doesn't really match the response. It would be nice if it said something about hitting an API limit and to try again in an hour or something.

**Comment by YahnisElsts** [comment] 2023-01-06 18:02
Right now PUC doesn't distinguish between different GitHub API errors. It just treats them all as failures.

I'll make a note to perhaps show different error messages if the error was caused by rate limiting specifically. Still, most users shouldn't usually see these errors unless they're manually checking for updates. The errors shouldn't show up during automatic checks - PUC should just retry later.

**Comment by JiveDig** [comment] 2023-01-06 18:04
Okay great, thanks. FWIW I've been using PUC for a few years now and it's been awesome. Thanks so much for sharing it, and your continued updates/support 🏆 ❤️

**Comment by YahnisElsts** [comment] 2023-01-06 18:13
Thanks, it's good to hear that the library is useful to people!

I'll close this issue now. The person who originally opened it hasn't commented here in a year, so, presumably, they have also resolved it somehow, or it's no longer relevant.

**Closed by YahnisElsts** 2023-01-06 18:14 UTC
