### ISSUE TITLE
Wordpress 4.2 plugin update from the Plugins Screen

### ISSUE THREAD

**Issue by bdtech** [YahnisElsts/plugin-update-checker#30] opened 2015-04-30 13:52 UTC
Wordpress 4.2 introduced a new update mechanism from the plugins page "update now" link alongside each plugin. I'm seeing "Update Failed" after clicking the "Update Now" link from wp-admin/plugins.php. Seems to work fine from Dashboard->Updates. Also, if you use the checkbox via bulk actions to update from plugins.php that works too. PHP error logs appear to be clean.

From 4.2 Codex: "More intuitive plugin update and install from the Plugins Screen. Goodbye boring loading screen, hello smooth and simple plugin updates. Click Update Now and watch the magic happen."

wp.ajax.post( 'update-plugin', data )
			.done( wp.updates.updateSuccess )
			.fail( wp.updates.updateError );

**Comment by YahnisElsts** [comment] 2015-04-30 15:17
Works For Me™. I tested the new "update now" link with [the example plugin](http://1.shadowcdn.com/files/external-update-example/external-update-example.zip), one of my commercial plugins, on a WP 4.2 + Centos server and on a WP 4.3-alpha + Windows machine. In all cases, the update was installed successfully.

- Can you post a minimal code example that reproduces the problem?
- Does it work with the example plugin? Note: For testing purposes, the "update" that the example plugin installs is actually identical to the old version.
- Are you doing anything unusual with your update package, like putting plugin files at the top of the archive or in a directory that doesn't match the plugin slug?

**Comment by bdtech** [comment] 2015-04-30 15:23
@YahnisElsts Sorry - found the issue. Tried to over tweak things for performance! 
if( defined( 'DOING_AJAX' ) && DOING_AJAX )
return;
require XYZ_PLUGIN_BASE . 'includes/plugin-update-checker.php';

**Comment by YahnisElsts** [comment] 2015-04-30 15:31
Yep, that would do it :-) Good to hear you figured it out. I'll close this issue now.

**Closed by YahnisElsts** 2015-04-30 15:31 UTC
